[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../../app" }

[build-dependencies]
risc0-build = { version = "1.2.0" }

[package.metadata.risc0]
methods = ["guest"]
