[package]
name = "goas_risc0_proofs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0" }

[package.metadata.risc0]
methods = ["spend_zone_funds", "zone_state", "user_atomic_transfer"]