[package]
name = "risc0-zkvm-io-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
risc0-zkvm-io = { path = "../risc0-zkvm-io" }

[lib]
proc-macro = true