[workspace]
resolver = "2"
members = [ "common", "executor", "proof_statements", "risc0_proofs", "user"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
