[package]
name = "goas_proof_statements"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
cl = { path = "../../cl/cl" }
serde = { version = "1.0", features = ["derive"] }
