[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
cl = { path = "../../cl/cl" }
proof_statements = { path = "../proof_statements", package = "goas_proof_statements" }
once_cell = "1"