[package]
name = "evm-sequencer-mempool"
edition = { workspace = true }

[dependencies]
eyre = { workspace = true }
reth = { workspace = true }
reth-node-ethereum = { workspace = true }
tokio = { workspace = true }
