[package]
name = "ledger_proof_statements"
version = "0.1.0"
edition = "2021"

[dependencies]
cl = { path = "../cl" }
serde = { version = "1.0", features = ["derive"] }
risc0-zkvm = "1.2"
risc0-zkvm-io = { path = "../risc0-zkvm-io" }
risc0-zkvm-io-derive = { path = "../risc0-zkvm-io-derive" }