[workspace]
members = ["evm/evm-node"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
# Internal
evm-node = { path = "evm/evm-node" }

# External
clap = { version = "4.5" }
futures-util = { version = "0.3" }
jsonrpsee = { version = "0.24" }
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.8" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.8" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.8" }
