[package]
name = "evm-node"
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
futures-util = { workspace = true }
jsonrpsee = { workspace = true }
reth = { workspace = true }
reth-cli-commands = { workspace = true }
reth-node-ethereum = { workspace = true }
